### ISSUE TITLE
macOS CI occasionally fails (MPI-related)

### ISSUE THREAD

**Issue by MakisH** [precice/precice#1390]
**Describe the problem**

Occasionally, the macOS CI fails, without a clear reason, even though most times is just works.

Here are some examples that look similar:

## Example 1

[PR](https://github.com/precice/precice/pull/1330), [job](https://github.com/precice/precice/runs/6970199054?check_suite_focus=true), failing test `precice.query`, error:

```
 A system call failed during shared memory initialization that should
not have.  It is likely that your MPI job will now either abort or
experience performance degradation.

  Local host:  Mac-1655739792923.local
  System call: unlink(2) /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T//ompi.Mac-1655739792923.501/pid.28893/1/vader_segment.Mac-1655739792923.501.9e610001.3
  Error:       No such file or directory (errno 2)
--------------------------------------------------------------------------
[Mac-1655739792923.local:28893] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2198
```

## Example 2

[PR](https://github.com/precice/precice/pull/1372#partial-pull-merging), [job](https://github.com/precice/precice/runs/7408168393?check_suite_focus=true), failing test `precice.solverdummy.run.cpp-c` (timeout), error:

```
A call to mkdir was unable to create the desired directory:

  Directory: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/ompi.Mac-1658207048453.501
  Error:     File exists

Please check to ensure you have adequate permissions to perform
the desired operation.
--------------------------------------------------------------------------
[Mac-1658207048453.local:17503] [[32558,0],0] ORTE_ERROR_LOG: Error in file util/session_dir.c at line 107
[Mac-1658207048453.local:17503] [[32558,0],0] ORTE_ERROR_LOG: Error in file util/session_dir.c at line 346
```

## Example 3

[PR](https://github.com/precice/precice/pull/1342), [job](https://github.com/precice/precice/runs/7503088164?check_suite_focus=true), failing test: `precice.acceleration` (timeout), no error given.

Rerunning the job just worked, so this must be a system/platform-specific issue, as well as difficult to reproduce.

**Step To Reproduce**

Unfortunately, not clear.

**Comment by fsimonis** [comment]
I suspect, that this was resolved by https://github.com/precice/precice/issues/1490

**Comment by davidscn** [comment]
We still face occasionally failing acceleration tests (see e.g. [this job run](https://github.com/precice/precice/actions/runs/3996108195/jobs/6855773734)). mac users also reported, that the acceleration tests takes sometimes suspiciously long.

**Comment by fsimonis** [comment]
I think that these problems disappeared after GitHub switched to the new ARM-based macOS runners.

Let's close and reopen once we notice problems.
