### ISSUE TITLE
run preCICE without network connection fails

### ISSUE THREAD

**Issue by scheufks** [precice/precice#45]
preCICE crashes if no network connection is available and communication is established via sockets.

**Comment by MakisH** [comment]
A maybe interesting aspect of this problem is that it also fails when connected to an **IPv6 network**. Currently, I can find this kind of networks as an alternative option (e.g. "eduroam-IPv6only" in TUM) but in some places they slowly start being enforced (e.g. in FOSDEM, the main Wi-Fi network this year was IPv6, with also an alternative for IPv4).

The exact error:
`[precice::com::SocketCommunication]:360 in requestConnection: Requesting connection to 127.0.0.1:45582 failed: resolve: Host not found (authoritative)`

**Comment by uekerman** [comment]
I just tried, but couldn't reproduce this (though it also happened to me some time ago). Does anybody have an update on this? Maybe this got fixed by a newer boost version?

**Comment by floli** [comment]
I can still confirm that bug:
from the elastictube:
```
 % ./FluidSolver ConfigurationFiles/precice-config.xml 100 0.01 100
Starting Fluid Solver...
N: 100 tau: 1.00000000000000002082e-02 kappa: 1.00000000000000000000e+02
Configure preCICE...
[2017-07-03 14:46:18.999884] [0x00007f422e474c00] [trace]   Entering configure
  Argument 0: configurationFileName == ConfigurationFiles/precice-config.xml
(0) 14:46:19 [impl::SolverInterfaceImpl]:176 in configure: [PRECICE] Run in coupling mode
Initialize preCICE...
(0) 14:46:19 [impl::SolverInterfaceImpl]:250 in initialize: Setting up master communication to coupling partner/s 
(0) 14:46:21 [precice::com::SocketCommunication]:360 in requestConnection: Requesting connection to 127.0.0.1:34137 failed: resolve: Host not found (authoritative)
```
Fails whenever either the network or wifi is deactivated using NetworkManager.

**Comment by MakisH** [comment]
I [partially solved this issue](https://github.com/MakisH/precice/commit/d3b2bc195d8ac4f45a73bbecf93b6b8ecf725aae) and I would like some help and feedback. My fix is based on [this StackOverflow answer](https://stackoverflow.com/a/24830462/2254346) and t[his commit on Monero](https://github.com/monero-project/monero/commit/c36cb5434059ed53daf947b189343ac0bd8f31d8).

Although it now works offline for simulations, it still does not work when I run the Boost tests (`./tools/compileAndTest.py -b`). Any idea what is different there?

I tested it locally on my laptop for the (serial) CHT OpenFOAM-OpenFOAM tutorial and for the parallel CHT OpenFOAM-CalculiX example that I am going to upload soon. It works both offline and online.

I have NOT tested it on the MAC Cluster/SuperMUC yet. When I make it also pass the Boost tests, I will issue a Pull Request.

[See the output of the boost tests here.](https://gist.github.com/MakisH/3d9b66563154d8f153003e2b609ee55d)

**Comment by floli** [comment]
Testing on your debug-#45 branch
Do you get the boost test failure with or without network connection?
With connection, I don't get that failure and the tests run fine (besides the occasional MPI error I get).

(more test follow, compiling right now)

**Comment by MakisH** [comment]
I get the boost test failure only without network connection. This is both for the develop and for the debug-#45 branch.

My patch only seems to cures the actual simulation.

**Comment by floli** [comment]
Test failure message is:
```
(1) 10:31:45 [cplscheme::BaseCouplingScheme]:734 in measureConvergence: All converged
(1) 10:31:45 [cplscheme::BaseCouplingScheme]:912 in timestepCompleted: Timestep completed
(0) 10:31:45 [cplscheme::BaseCouplingScheme]:912 in timestepCompleted: Timestep completed
(1) 10:31:47 [precice::com::SocketCommunication]:415 in requestConnectionAsClient: ERROR: Requesting connection to  failed: resolve: Host not found (authoritative)
(0) 10:31:47 [precice::com::SocketCommunication]:415 in requestConnectionAsClient: ERROR: Requesting connection to  failed: resolve: Host not found (authoritative)
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::log::v2_mt_posix::system_error> >'
  what():  Failed to set TLS value: Invalid argument
[asaru:17422] *** Process received signal ***
[asaru:17422] Signal: Aborted (6)
[asaru:17422] Signal code:  (-6)
[asaru:17422] [ 0] /usr/lib/libpthread.so.0(+0x11dd0)[0x7f4ef174cdd0]
[asaru:17422] [ 1] /usr/lib/libc.so.6(gsignal+0x110)[0x7f4eecfa0860]
[asaru:17422] [ 2] /usr/lib/libc.so.6(abort+0x1c9)[0x7f4eecfa1ec9]
[asaru:17422] [ 3] /usr/lib/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x147)[0x7f4eed914d57]
[asaru:17422] [ 4] /usr/lib/libstdc++.so.6(+0x8c8c6)[0x7f4eed9128c6]
[asaru:17422] [ 5] /usr/lib/libstdc++.so.6(+0x8c913)[0x7f4eed912913]
[asaru:17422] [ 6] /usr/lib/libstdc++.so.6(+0x8c926)[0x7f4eed912926]
[asaru:17422] [ 7] /usr/lib/libstdc++.so.6(__cxa_call_unexpected+0x44)[0x7f4eed912534]
[asaru:17422] [ 8] terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::log::v2_mt_posix::system_error> >'
  what():  Failed to set TLS value: Invalid argument
[asaru:17421] *** Process received signal ***
[asaru:17421] Signal: Aborted (6)
[asaru:17421] Signal code:  (-6)
../build/last/testprecice(_ZN7precice7logging6TracerD2Ev+0x66d)[0x561f5659522d]
[asaru:17422] [ 9] [asaru:17421] [ 0] /usr/lib/libpthread.so.0(+0x11dd0)[0x7f37b46a9dd0]
[asaru:17421] [ 1] /usr/lib/libc.so.6(gsignal+0x110)[0x7f37afefd860]
[asaru:17421] [ 2] ../build/last/testprecice(_ZN7precice3com22MPIDirectCommunicationD1Ev+0x9aa)[0x561f56204a1a]
[asaru:17422] [10] /usr/lib/libc.so.6(abort+0x1c9)[0x7f37afefeec9]
[asaru:17421] [ 3] /usr/lib/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x147)[0x7f37b0871d57]
[asaru:17421] [ 4] /usr/lib/libstdc++.so.6(+0x8c8c6)[0x7f37b086f8c6]
[asaru:17421] [ 5] ../build/last/testprecice(_ZN9__gnu_cxx13new_allocatorIN7precice3com22MPIDirectCommunicationEE7destroyIS3_EEvPT_+0x24)[0x561f5628cae4]
[asaru:17422] [11] /usr/lib/libstdc++.so.6(+0x8c913)[0x7f37b086f913]
[asaru:17421] [ 6] /usr/lib/libstdc++.so.6(+0x8c926)[0x7f37b086f926]
[asaru:17421] [ 7] /usr/lib/libstdc++.so.6(__cxa_call_unexpected+0x44)[0x7f37b086f534]
[asaru:17421] [ 8] ../build/last/testprecice(_ZNSt16allocator_traitsISaIN7precice3com22MPIDirectCommunicationEEE7destroyIS2_EEvRS3_PT_+0x28)[0x561f5628ca78]
[asaru:17422] [12] ../build/last/testprecice(_ZNSt23_Sp_counted_ptr_inplaceIN7precice3com22MPIDirectCommunicationESaIS2_ELN9__gnu_cxx12_Lock_policyE2EE10_M_disposeEv+0x3c)[0x561f5628c85c]
[asaru:17422] [13] ../build/last/testprecice(_ZNSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE10_M_releaseEv+0x4c)[0x561f56191e5c]
[asaru:17422] [14] ../build/last/testprecice(_ZN7precice7logging6TracerD2Ev+0x66d)[0x5577e725422d]
[asaru:17421] [ 9] ../build/last/testprecice(_ZNSt14__shared_countILN9__gnu_cxx12_Lock_policyE2EED2Ev+0x2a)[0x561f56191e0a]
[asaru:17422] [15] ../build/last/testprecice(_ZN7precice3com22MPIDirectCommunicationD1Ev+0x9aa)[0x5577e6ec3a1a]
[asaru:17421] [10] ../build/last/testprecice(_ZNSt12__shared_ptrIN7precice3com13CommunicationELN9__gnu_cxx12_Lock_policyE2EED2Ev+0x19)[0x561f5628b3f9]
[asaru:17422] [16] ../build/last/testprecice(_ZNSt10shared_ptrIN7precice3com13CommunicationEED2Ev+0x15)[0x561f5628a2c5]
[asaru:17422] [17] /usr/lib/libc.so.6(+0x37448)[0x7f4eecfa3448]
[asaru:17422] [18] /usr/lib/libc.so.6(+0x3749a)[0x7f4eecfa349a]
[asaru:17422] [19] ../build/last/testprecice(_ZN9__gnu_cxx13new_allocatorIN7precice3com22MPIDirectCommunicationEE7destroyIS3_EEvPT_+0x24)[0x5577e6f4bae4]
[asaru:17421] [11] ../build/last/testprecice(_ZN7precice3com19SocketCommunication25requestConnectionAsClientERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_+0x370e)[0x561f56240b4e]
[asaru:17422] [20] ../build/last/testprecice(_ZNSt16allocator_traitsISaIN7precice3com22MPIDirectCommunicationEEE7destroyIS2_EEvRS3_PT_+0x28)[0x5577e6f4ba78]
[asaru:17421] [12] ../build/last/testprecice(_ZN7precice3m2n25PointToPointCommunication17requestConnectionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_+0x228a)[0x561f565b7baa]
[asaru:17422] [21] ../build/last/testprecice(_ZNSt23_Sp_counted_ptr_inplaceIN7precice3com22MPIDirectCommunicationESaIS2_ELN9__gnu_cxx12_Lock_policyE2EE10_M_disposeEv+0x3c)[0x5577e6f4b85c]
[asaru:17421] [13] ../build/last/testprecice(_ZN8M2NTests11P2PComTest1ESt10shared_ptrIN7precice3com20CommunicationFactoryEE+0x18d1)[0x561f56b658e1]
[asaru:17422] [22] ../build/last/testprecice(_ZNSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE10_M_releaseEv+0x4c)[0x5577e6e50e5c]
[asaru:17421] [14] ../build/last/testprecice(_ZN8M2NTests19SocketCommunication11test_methodEv+0x142)[0x561f56b691a2]
[asaru:17422] [23] ../build/last/testprecice(_ZNSt14__shared_countILN9__gnu_cxx12_Lock_policyE2EED2Ev+0x2a)[0x5577e6e50e0a]
[asaru:17421] [15] ../build/last/testprecice(+0x1452d11)[0x561f56b68d11]
[asaru:17422] [24] ../build/last/testprecice(_ZNSt12__shared_ptrIN7precice3com13CommunicationELN9__gnu_cxx12_Lock_policyE2EED2Ev+0x19)[0x5577e6f4a3f9]
[asaru:17421] [16] ../build/last/testprecice(_ZNSt10shared_ptrIN7precice3com13CommunicationEED2Ev+0x15)[0x5577e6f492c5]
[asaru:17421] [17] ../build/last/testprecice(_ZN5boost6detail8function22void_function_invoker0IPFvvEvE6invokeERNS1_15function_bufferE+0x1a)[0x561f56a1006a]
[asaru:17422] [25] /usr/lib/libboost_unit_test_framework.so.1.66.0(_ZN5boost6detail8function21function_obj_invoker0INS0_7forwardEiE6invokeERNS1_15function_bufferE+0x2e)[0x7f4eee929bfe]
[asaru:17422] [26] /usr/lib/libboost_unit_test_framework.so.1.66.0(_ZN5boost17execution_monitor13catch_signalsERKNS_8functionIFivEEE+0x145)[0x7f4eee929035]
[asaru:17422] [27] /usr/lib/libboost_unit_test_framework.so.1.66.0(_ZN5boost17execution_monitor7executeERKNS_8functionIFivEEE+0x54)[0x7f4eee929124]
[asaru:17422] [28] /usr/lib/libboost_unit_test_framework.so.1.66.0(_ZN5boost17execution_monitor8vexecuteERKNS_8functionIFvvEEE+0x5f)[0x7f4eee9298ef]
[asaru:17422] [29] /usr/lib/libboost_unit_test_framework.so.1.66.0(_ZN5boost9unit_test19unit_test_monitor_t21execute_and_translateERKNS_8functionIFvvEEEj+0x872)[0x7f4eee9590c2]
[asaru:17422] *** End of error message ***
/usr/lib/libc.so.6(+0x37448)[0x7f37aff00448]
[asaru:17421] [18] /usr/lib/libc.so.6(+0x3749a)[0x7f37aff0049a]
[asaru:17421] [19] ../build/last/testprecice(_ZN7precice3com19SocketCommunication25requestConnectionAsClientERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_+0x370e)[0x5577e6effb4e]
[asaru:17421] [20] ../build/last/testprecice(_ZN7precice3m2n25PointToPointCommunication17requestConnectionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_+0x228a)[0x5577e7276baa]
[asaru:17421] [21] ../build/last/testprecice(_ZN8M2NTests11P2PComTest1ESt10shared_ptrIN7precice3com20CommunicationFactoryEE+0x18d1)[0x5577e78248e1]
[asaru:17421] [22] ../build/last/testprecice(_ZN8M2NTests19SocketCommunication11test_methodEv+0x142)[0x5577e78281a2]
[asaru:17421] [23] ../build/last/testprecice(+0x1452d11)[0x5577e7827d11]
[asaru:17421] [24] ../build/last/testprecice(_ZN5boost6detail8function22void_function_invoker0IPFvvEvE6invokeERNS1_15function_bufferE+0x1a)[0x5577e76cf06a]
[asaru:17421] [25] /usr/lib/libboost_unit_test_framework.so.1.66.0(_ZN5boost6detail8function21function_obj_invoker0INS0_7forwardEiE6invokeERNS1_15function_bufferE+0x2e)[0x7f37b1886bfe]
[asaru:17421] [26] /usr/lib/libboost_unit_test_framework.so.1.66.0(_ZN5boost17execution_monitor13catch_signalsERKNS_8functionIFivEEE+0x145)[0x7f37b1886035]
[asaru:17421] [27] /usr/lib/libboost_unit_test_framework.so.1.66.0(_ZN5boost17execution_monitor7executeERKNS_8functionIFivEEE+0x54)[0x7f37b1886124]
[asaru:17421] [28] /usr/lib/libboost_unit_test_framework.so.1.66.0(_ZN5boost17execution_monitor8vexecuteERKNS_8functionIFvvEEE+0x5f)[0x7f37b18868ef]
[asaru:17421] [29] /usr/lib/libboost_unit_test_framework.so.1.66.0(_ZN5boost9unit_test19unit_test_monitor_t21execute_and_translateERKNS_8functionIFvvEEEj+0x872)[0x7f37b18b60c2]
[asaru:17421] *** End of error message ***
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 2 in communicator MPI_COMM_WORLD
with errorcode 59.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[3]PETSC ERROR: ------------------------------------------------------------------------
[3]PETSC ERROR: Caught signal number 15 Terminate: Some process (or the batch system) has told this process to end
[3]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[3]PETSC ERROR: or see http://www.mcs.anl.gov/petsc/documentation/faq.html#valgrind
[3]PETSC ERROR: or try http://valgrind.org on GNU/linux and Apple Mac OS X to find memory corruption errors
[3]PETSC ERROR: likely location of problem given in stack below
[3]PETSC ERROR: ---------------------  Stack Frames ------------------------------------
[3]PETSC ERROR: Note: The EXACT line numbers in the stack are not available,
[3]PETSC ERROR:       INSTEAD the line number of the start of the function
[3]PETSC ERROR:       is given.
[3]PETSC ERROR: User provided function() line 0 in  unknown file
[2]PETSC ERROR: ------------------------------------------------------------------------
[2]PETSC ERROR: Caught signal number 15 Terminate: Some process (or the batch system) has told this process to end
[2]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[2]PETSC ERROR: or see http://www.mcs.anl.gov/petsc/documentation/faq.html#valgrind
[2]PETSC ERROR: or try http://valgrind.org on GNU/linux and Apple Mac OS X to find memory corruption errors
[2]PETSC ERROR: likely location of problem given in stack below
[2]PETSC ERROR: ---------------------  Stack Frames ------------------------------------
[2]PETSC ERROR: Note: The EXACT line numbers in the stack are not available,
[2]PETSC ERROR:       INSTEAD the line number of the start of the function
[2]PETSC ERROR:       is given.
[2]PETSC ERROR: User provided function() line 0 in  unknown file
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node asaru exited on signal 6 (Aborted).
--------------------------------------------------------------------------
[asaru:17416] 1 more process has sent help message help-mpi-api.txt / mpi-abort
[asaru:17416] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

**Comment by MakisH** [comment]
A more detailed description of the patch:
In [src/com/SocketCommunication.cpp](https://github.com/precice/precice/blob/develop/src/com/SocketCommunication.cpp) there is this line:

```c++
tcp::resolver::query query(tcp::v4(), ipAddress, portNumber);
```

which I changed to:

```c++
tcp::resolver::query query(tcp::v4(), ipAddress, portNumber, tcp::resolver::query::canonical_name);
```

If we don't specify `tcp::resolver::query::canonical_name`, it defaults to `tcp::resolver::query::address_configured`.

There are also [other alternatives](http://www.boost.org/doc/libs/1_47_0/doc/html/boost_asio/reference/ip__basic_resolver/query.html), which I will try.

**Comment by floli** [comment]
Just curious, is there any specific reason why we limit it to IPv4? After all, we want to be future proof ;-)

**Comment by MakisH** [comment]
I tried all the different values of `ip::basic_resolver::query`. None works with `compileAndTest.py -b`.

* The default (`address_configured`) fails both the Boost tests and the Simulations. The error in this case shows the IP address that can't be found.
* Everything else fails th Boost tests but not the Simulations. The error in this case does not show the IP address.

**Comment by MakisH** [comment]
Actually this now looks completely fixed for me. Both with and without network, simulations, as well as the tests work well. I tested the OpenFOAM-OpenFOAM flat plate tutorial, as well as the SU2-CalculiX flap tutorial, both in serial and in parallel.

I have not tested this with IPv6 networks yet.
I use Boost 1.65.1 on Ubuntu 16.04 (OpenMPI 1.10.2).

**Comment by hanok-e** [comment]
Encountered this error while trying to run cylinderFlap case with OpenFoam/CalculiX
`Requesting a socket connection at 127.0.0.1:42873 failed with the system error: resolve: Host not found (authoritative)`


[Fluid.log](https://github.com/precice/precice/files/5976234/Fluid.log)

**Comment by fsimonis** [comment]
I rewrote the back-end in order to emit more informative error messages in https://github.com/precice/precice/commit/4111614601b75cc300f426d689cbe6df801167f5.
This also includes a fix for unconnected interfaces https://github.com/precice/precice/commit/08edebecede6cd9bc588b86ae398d682a398880e.
All of this was released in version 2.1.0

We should check if these changes resolved the issue.

**Comment by fsimonis** [comment]
This issue wasn't fixed. I can still reproduce it with the current develop version https://github.com/precice/precice/commit/08edebecede6cd9bc588b86ae398d682a398880e.
